// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/library_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_MOVIE       MediaType = 1
	MediaType_MEDIA_TYPE_TV          MediaType = 2
	MediaType_MEDIA_TYPE_BOOK        MediaType = 3
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_MOVIE",
		2: "MEDIA_TYPE_TV",
		3: "MEDIA_TYPE_BOOK",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_MOVIE":       1,
		"MEDIA_TYPE_TV":          2,
		"MEDIA_TYPE_BOOK":        3,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_library_model_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_models_library_model_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{0}
}

type EntryStatus int32

const (
	EntryStatus_ENTRY_STATUS_UNSPECIFIED EntryStatus = 0
	EntryStatus_ENTRY_STATUS_PLANNED     EntryStatus = 1
	EntryStatus_ENTRY_STATUS_IN_PROGRESS EntryStatus = 2
	EntryStatus_ENTRY_STATUS_DONE        EntryStatus = 3
)

// Enum value maps for EntryStatus.
var (
	EntryStatus_name = map[int32]string{
		0: "ENTRY_STATUS_UNSPECIFIED",
		1: "ENTRY_STATUS_PLANNED",
		2: "ENTRY_STATUS_IN_PROGRESS",
		3: "ENTRY_STATUS_DONE",
	}
	EntryStatus_value = map[string]int32{
		"ENTRY_STATUS_UNSPECIFIED": 0,
		"ENTRY_STATUS_PLANNED":     1,
		"ENTRY_STATUS_IN_PROGRESS": 2,
		"ENTRY_STATUS_DONE":        3,
	}
)

func (x EntryStatus) Enum() *EntryStatus {
	p := new(EntryStatus)
	*p = x
	return p
}

func (x EntryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_models_library_model_proto_enumTypes[1].Descriptor()
}

func (EntryStatus) Type() protoreflect.EnumType {
	return &file_models_library_model_proto_enumTypes[1]
}

func (x EntryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryStatus.Descriptor instead.
func (EntryStatus) EnumDescriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{1}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       uint64                 `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	MediaId       uint64                 `protobuf:"varint,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Type          MediaType              `protobuf:"varint,3,opt,name=type,proto3,enum=library.models.v1.MediaType" json:"type,omitempty"`
	Status        EntryStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=library.models.v1.EntryStatus" json:"status,omitempty"`
	Rating        uint32                 `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Review        string                 `protobuf:"bytes,6,opt,name=review,proto3" json:"review,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_models_library_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *Entry) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *Entry) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *Entry) GetStatus() EntryStatus {
	if x != nil {
		return x.Status
	}
	return EntryStatus_ENTRY_STATUS_UNSPECIFIED
}

func (x *Entry) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Entry) GetReview() string {
	if x != nil {
		return x.Review
	}
	return ""
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Entry) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint64                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Type          MediaType              `protobuf:"varint,2,opt,name=type,proto3,enum=library.models.v1.MediaType" json:"type,omitempty"`
	Status        EntryStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=library.models.v1.EntryStatus" json:"status,omitempty"`
	Rating        uint32                 `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Review        string                 `protobuf:"bytes,5,opt,name=review,proto3" json:"review,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_models_library_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntryRequest) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *CreateEntryRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *CreateEntryRequest) GetStatus() EntryStatus {
	if x != nil {
		return x.Status
	}
	return EntryStatus_ENTRY_STATUS_UNSPECIFIED
}

func (x *CreateEntryRequest) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateEntryRequest) GetReview() string {
	if x != nil {
		return x.Review
	}
	return ""
}

func (x *CreateEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateEntryRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CreateEntryRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type UpdateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       uint64                 `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Status        *EntryStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=library.models.v1.EntryStatus,oneof" json:"status,omitempty"`
	Rating        *uint32                `protobuf:"varint,3,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Review        *string                `protobuf:"bytes,4,opt,name=review,proto3,oneof" json:"review,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryRequest) Reset() {
	*x = UpdateEntryRequest{}
	mi := &file_models_library_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryRequest) ProtoMessage() {}

func (x *UpdateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEntryRequest) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *UpdateEntryRequest) GetStatus() EntryStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EntryStatus_ENTRY_STATUS_UNSPECIFIED
}

func (x *UpdateEntryRequest) GetRating() uint32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *UpdateEntryRequest) GetReview() string {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return ""
}

func (x *UpdateEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateEntryRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *UpdateEntryRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type DeleteEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       uint64                 `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_models_library_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteEntryRequest) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       uint64                 `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_models_library_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntryRequest) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []MediaType            `protobuf:"varint,1,rep,packed,name=types,proto3,enum=library.models.v1.MediaType" json:"types,omitempty"`
	Statuses      []EntryStatus          `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=library.models.v1.EntryStatus" json:"statuses,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	MinRating     uint32                 `protobuf:"varint,4,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	MaxRating     uint32                 `protobuf:"varint,5,opt,name=max_rating,json=maxRating,proto3" json:"max_rating,omitempty"`
	FinishedFrom  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_from,json=finishedFrom,proto3,oneof" json:"finished_from,omitempty"`
	FinishedTo    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_to,json=finishedTo,proto3,oneof" json:"finished_to,omitempty"`
	SortBy        string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Page          uint32                 `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,11,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_models_library_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{5}
}

func (x *ListEntriesRequest) GetTypes() []MediaType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ListEntriesRequest) GetStatuses() []EntryStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListEntriesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListEntriesRequest) GetMinRating() uint32 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *ListEntriesRequest) GetMaxRating() uint32 {
	if x != nil {
		return x.MaxRating
	}
	return 0
}

func (x *ListEntriesRequest) GetFinishedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedFrom
	}
	return nil
}

func (x *ListEntriesRequest) GetFinishedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedTo
	}
	return nil
}

func (x *ListEntriesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListEntriesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListEntriesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEntriesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_models_library_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{6}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListEntriesResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEntriesResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEntriesResponse) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type EntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryResponse) Reset() {
	*x = EntryResponse{}
	mi := &file_models_library_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryResponse) ProtoMessage() {}

func (x *EntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryResponse.ProtoReflect.Descriptor instead.
func (*EntryResponse) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{7}
}

func (x *EntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_models_library_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_library_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryResponse) Descriptor() ([]byte, []int) {
	return file_models_library_model_proto_rawDescGZIP(), []int{8}
}

var File_models_library_model_proto protoreflect.FileDescriptor

const file_models_library_model_proto_rawDesc = "" +
	"\n" +
	"\x1amodels/library_model.proto\x12\x11library.models.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x03\n" +
	"\x05Entry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x04R\aentryId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\x04R\amediaId\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.library.models.v1.MediaTypeR\x04type\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.library.models.v1.EntryStatusR\x06status\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\rR\x06rating\x12\x16\n" +
	"\x06review\x18\x06 \x01(\tR\x06review\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd5\x02\n" +
	"\x12CreateEntryRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x04R\amediaId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.library.models.v1.MediaTypeR\x04type\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1e.library.models.v1.EntryStatusR\x06status\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\rR\x06rating\x12\x16\n" +
	"\x06review\x18\x05 \x01(\tR\x06review\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xfc\x02\n" +
	"\x12UpdateEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x04R\aentryId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.library.models.v1.EntryStatusH\x00R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\x03 \x01(\rH\x01R\x06rating\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\x04 \x01(\tH\x02R\x06review\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12>\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tstartedAt\x88\x01\x01\x12@\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\n" +
	"finishedAt\x88\x01\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_ratingB\t\n" +
	"\a_reviewB\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_at\"/\n" +
	"\x12DeleteEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x04R\aentryId\",\n" +
	"\x0fGetEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x04R\aentryId\"\xe9\x03\n" +
	"\x12ListEntriesRequest\x122\n" +
	"\x05types\x18\x01 \x03(\x0e2\x1c.library.models.v1.MediaTypeR\x05types\x12:\n" +
	"\bstatuses\x18\x02 \x03(\x0e2\x1e.library.models.v1.EntryStatusR\bstatuses\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x04 \x01(\rR\tminRating\x12\x1d\n" +
	"\n" +
	"max_rating\x18\x05 \x01(\rR\tmaxRating\x12D\n" +
	"\rfinished_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ffinishedFrom\x88\x01\x01\x12@\n" +
	"\vfinished_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"finishedTo\x88\x01\x01\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\tR\tsortOrder\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\v \x01(\rR\bpageSizeB\x10\n" +
	"\x0e_finished_fromB\x0e\n" +
	"\f_finished_to\"\xb1\x01\n" +
	"\x13ListEntriesResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.library.models.v1.EntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\rR\n" +
	"totalPages\"?\n" +
	"\rEntryResponse\x12.\n" +
	"\x05entry\x18\x01 \x01(\v2\x18.library.models.v1.EntryR\x05entry\"\x15\n" +
	"\x13DeleteEntryResponse*e\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_MOVIE\x10\x01\x12\x11\n" +
	"\rMEDIA_TYPE_TV\x10\x02\x12\x13\n" +
	"\x0fMEDIA_TYPE_BOOK\x10\x03*z\n" +
	"\vEntryStatus\x12\x1c\n" +
	"\x18ENTRY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENTRY_STATUS_PLANNED\x10\x01\x12\x1c\n" +
	"\x18ENTRY_STATUS_IN_PROGRESS\x10\x02\x12\x15\n" +
	"\x11ENTRY_STATUS_DONE\x10\x03BBZ@github.com/vbncursed/medialog/library_service/internal/pb/modelsb\x06proto3"

var (
	file_models_library_model_proto_rawDescOnce sync.Once
	file_models_library_model_proto_rawDescData []byte
)

func file_models_library_model_proto_rawDescGZIP() []byte {
	file_models_library_model_proto_rawDescOnce.Do(func() {
		file_models_library_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_library_model_proto_rawDesc), len(file_models_library_model_proto_rawDesc)))
	})
	return file_models_library_model_proto_rawDescData
}

var file_models_library_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_library_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_models_library_model_proto_goTypes = []any{
	(MediaType)(0),                // 0: library.models.v1.MediaType
	(EntryStatus)(0),              // 1: library.models.v1.EntryStatus
	(*Entry)(nil),                 // 2: library.models.v1.Entry
	(*CreateEntryRequest)(nil),    // 3: library.models.v1.CreateEntryRequest
	(*UpdateEntryRequest)(nil),    // 4: library.models.v1.UpdateEntryRequest
	(*DeleteEntryRequest)(nil),    // 5: library.models.v1.DeleteEntryRequest
	(*GetEntryRequest)(nil),       // 6: library.models.v1.GetEntryRequest
	(*ListEntriesRequest)(nil),    // 7: library.models.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),   // 8: library.models.v1.ListEntriesResponse
	(*EntryResponse)(nil),         // 9: library.models.v1.EntryResponse
	(*DeleteEntryResponse)(nil),   // 10: library.models.v1.DeleteEntryResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_models_library_model_proto_depIdxs = []int32{
	0,  // 0: library.models.v1.Entry.type:type_name -> library.models.v1.MediaType
	1,  // 1: library.models.v1.Entry.status:type_name -> library.models.v1.EntryStatus
	11, // 2: library.models.v1.Entry.started_at:type_name -> google.protobuf.Timestamp
	11, // 3: library.models.v1.Entry.finished_at:type_name -> google.protobuf.Timestamp
	11, // 4: library.models.v1.Entry.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: library.models.v1.Entry.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: library.models.v1.CreateEntryRequest.type:type_name -> library.models.v1.MediaType
	1,  // 7: library.models.v1.CreateEntryRequest.status:type_name -> library.models.v1.EntryStatus
	11, // 8: library.models.v1.CreateEntryRequest.started_at:type_name -> google.protobuf.Timestamp
	11, // 9: library.models.v1.CreateEntryRequest.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 10: library.models.v1.UpdateEntryRequest.status:type_name -> library.models.v1.EntryStatus
	11, // 11: library.models.v1.UpdateEntryRequest.started_at:type_name -> google.protobuf.Timestamp
	11, // 12: library.models.v1.UpdateEntryRequest.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 13: library.models.v1.ListEntriesRequest.types:type_name -> library.models.v1.MediaType
	1,  // 14: library.models.v1.ListEntriesRequest.statuses:type_name -> library.models.v1.EntryStatus
	11, // 15: library.models.v1.ListEntriesRequest.finished_from:type_name -> google.protobuf.Timestamp
	11, // 16: library.models.v1.ListEntriesRequest.finished_to:type_name -> google.protobuf.Timestamp
	2,  // 17: library.models.v1.ListEntriesResponse.entries:type_name -> library.models.v1.Entry
	2,  // 18: library.models.v1.EntryResponse.entry:type_name -> library.models.v1.Entry
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_models_library_model_proto_init() }
func file_models_library_model_proto_init() {
	if File_models_library_model_proto != nil {
		return
	}
	file_models_library_model_proto_msgTypes[2].OneofWrappers = []any{}
	file_models_library_model_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_library_model_proto_rawDesc), len(file_models_library_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_library_model_proto_goTypes,
		DependencyIndexes: file_models_library_model_proto_depIdxs,
		EnumInfos:         file_models_library_model_proto_enumTypes,
		MessageInfos:      file_models_library_model_proto_msgTypes,
	}.Build()
	File_models_library_model_proto = out.File
	file_models_library_model_proto_goTypes = nil
	file_models_library_model_proto_depIdxs = nil
}
