// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth_api/auth.proto

package auth_api

import (
	models "github.com/vbncursed/medialog/auth_service/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_api_auth_proto protoreflect.FileDescriptor

const file_auth_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x13auth_api/auth.proto\x12\x0fauth.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17models/auth_model.proto2\x90\x04\n" +
	"\vAuthService\x12g\n" +
	"\bRegister\x12\x1f.auth.models.v1.RegisterRequest\x1a\x1c.auth.models.v1.AuthResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12^\n" +
	"\x05Login\x12\x1c.auth.models.v1.LoginRequest\x1a\x1c.auth.models.v1.AuthResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12d\n" +
	"\aRefresh\x12\x1e.auth.models.v1.RefreshRequest\x1a\x1c.auth.models.v1.AuthResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12c\n" +
	"\x06Logout\x12\x1d.auth.models.v1.LogoutRequest\x1a\x1e.auth.models.v1.LogoutResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12m\n" +
	"\tLogoutAll\x12 .auth.models.v1.LogoutAllRequest\x1a\x1e.auth.models.v1.LogoutResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/auth/logout-allBAZ?github.com/vbncursed/medialog/auth_service/internal/pb/auth_apib\x06proto3"

var file_auth_api_auth_proto_goTypes = []any{
	(*models.RegisterRequest)(nil),  // 0: auth.models.v1.RegisterRequest
	(*models.LoginRequest)(nil),     // 1: auth.models.v1.LoginRequest
	(*models.RefreshRequest)(nil),   // 2: auth.models.v1.RefreshRequest
	(*models.LogoutRequest)(nil),    // 3: auth.models.v1.LogoutRequest
	(*models.LogoutAllRequest)(nil), // 4: auth.models.v1.LogoutAllRequest
	(*models.AuthResponse)(nil),     // 5: auth.models.v1.AuthResponse
	(*models.LogoutResponse)(nil),   // 6: auth.models.v1.LogoutResponse
}
var file_auth_api_auth_proto_depIdxs = []int32{
	0, // 0: auth.service.v1.AuthService.Register:input_type -> auth.models.v1.RegisterRequest
	1, // 1: auth.service.v1.AuthService.Login:input_type -> auth.models.v1.LoginRequest
	2, // 2: auth.service.v1.AuthService.Refresh:input_type -> auth.models.v1.RefreshRequest
	3, // 3: auth.service.v1.AuthService.Logout:input_type -> auth.models.v1.LogoutRequest
	4, // 4: auth.service.v1.AuthService.LogoutAll:input_type -> auth.models.v1.LogoutAllRequest
	5, // 5: auth.service.v1.AuthService.Register:output_type -> auth.models.v1.AuthResponse
	5, // 6: auth.service.v1.AuthService.Login:output_type -> auth.models.v1.AuthResponse
	5, // 7: auth.service.v1.AuthService.Refresh:output_type -> auth.models.v1.AuthResponse
	6, // 8: auth.service.v1.AuthService.Logout:output_type -> auth.models.v1.LogoutResponse
	6, // 9: auth.service.v1.AuthService.LogoutAll:output_type -> auth.models.v1.LogoutResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_api_auth_proto_init() }
func file_auth_api_auth_proto_init() {
	if File_auth_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_api_auth_proto_rawDesc), len(file_auth_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_api_auth_proto_goTypes,
		DependencyIndexes: file_auth_api_auth_proto_depIdxs,
	}.Build()
	File_auth_api_auth_proto = out.File
	file_auth_api_auth_proto_goTypes = nil
	file_auth_api_auth_proto_depIdxs = nil
}
