// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: metadata_api/metadata.proto

package metadata_api

import (
	metadata_models "github.com/vbncursed/medialog/library_service/internal/pb/metadata_models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_metadata_api_metadata_proto protoreflect.FileDescriptor

const file_metadata_api_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1bmetadata_api/metadata.proto\x12\x13metadata.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a$metadata_models/metadata_model.proto2\xb7\x04\n" +
	"\x0fMetadataService\x12~\n" +
	"\vSearchMedia\x12&.metadata.models.v1.SearchMediaRequest\x1a'.metadata.models.v1.SearchMediaResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/metadata/search\x12|\n" +
	"\bGetMedia\x12#.metadata.models.v1.GetMediaRequest\x1a$.metadata.models.v1.GetMediaResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/metadata/media/{media_id}\x12\xa9\x01\n" +
	"\x14GetMediaByExternalID\x12/.metadata.models.v1.GetMediaByExternalIDRequest\x1a$.metadata.models.v1.GetMediaResponse\":\x82\xd3\xe4\x93\x024\x122/v1/metadata/media/external/{source}/{external_id}\x12z\n" +
	"\vCreateMedia\x12&.metadata.models.v1.CreateMediaRequest\x1a$.metadata.models.v1.GetMediaResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/metadata/mediaBHZFgithub.com/vbncursed/medialog/library_service/internal/pb/metadata_apib\x06proto3"

var file_metadata_api_metadata_proto_goTypes = []any{
	(*metadata_models.SearchMediaRequest)(nil),          // 0: metadata.models.v1.SearchMediaRequest
	(*metadata_models.GetMediaRequest)(nil),             // 1: metadata.models.v1.GetMediaRequest
	(*metadata_models.GetMediaByExternalIDRequest)(nil), // 2: metadata.models.v1.GetMediaByExternalIDRequest
	(*metadata_models.CreateMediaRequest)(nil),          // 3: metadata.models.v1.CreateMediaRequest
	(*metadata_models.SearchMediaResponse)(nil),         // 4: metadata.models.v1.SearchMediaResponse
	(*metadata_models.GetMediaResponse)(nil),            // 5: metadata.models.v1.GetMediaResponse
}
var file_metadata_api_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.service.v1.MetadataService.SearchMedia:input_type -> metadata.models.v1.SearchMediaRequest
	1, // 1: metadata.service.v1.MetadataService.GetMedia:input_type -> metadata.models.v1.GetMediaRequest
	2, // 2: metadata.service.v1.MetadataService.GetMediaByExternalID:input_type -> metadata.models.v1.GetMediaByExternalIDRequest
	3, // 3: metadata.service.v1.MetadataService.CreateMedia:input_type -> metadata.models.v1.CreateMediaRequest
	4, // 4: metadata.service.v1.MetadataService.SearchMedia:output_type -> metadata.models.v1.SearchMediaResponse
	5, // 5: metadata.service.v1.MetadataService.GetMedia:output_type -> metadata.models.v1.GetMediaResponse
	5, // 6: metadata.service.v1.MetadataService.GetMediaByExternalID:output_type -> metadata.models.v1.GetMediaResponse
	5, // 7: metadata.service.v1.MetadataService.CreateMedia:output_type -> metadata.models.v1.GetMediaResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_api_metadata_proto_init() }
func file_metadata_api_metadata_proto_init() {
	if File_metadata_api_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_api_metadata_proto_rawDesc), len(file_metadata_api_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadata_api_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_api_metadata_proto_depIdxs,
	}.Build()
	File_metadata_api_metadata_proto = out.File
	file_metadata_api_metadata_proto_goTypes = nil
	file_metadata_api_metadata_proto_depIdxs = nil
}
