// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/vbncursed/medialog/auth_service/internal/models"
)

// NewAuthStorage creates a new instance of AuthStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthStorage {
	mock := &AuthStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthStorage is an autogenerated mock type for the AuthStorage type
type AuthStorage struct {
	mock.Mock
}

type AuthStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthStorage) EXPECT() *AuthStorage_Expecter {
	return &AuthStorage_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type AuthStorage
func (_mock *AuthStorage) CreateUser(ctx context.Context, email string, passwordHash string) (uint64, error) {
	ret := _mock.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uint64, error)); ok {
		return returnFunc(ctx, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uint64); ok {
		r0 = returnFunc(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type AuthStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *AuthStorage_Expecter) CreateUser(ctx interface{}, email interface{}, passwordHash interface{}) *AuthStorage_CreateUser_Call {
	return &AuthStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash)}
}

func (_c *AuthStorage_CreateUser_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *AuthStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthStorage_CreateUser_Call) Return(v uint64, err error) *AuthStorage_CreateUser_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AuthStorage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, email string, passwordHash string) (uint64, error)) *AuthStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type AuthStorage
func (_mock *AuthStorage) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthStorage_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type AuthStorage_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthStorage_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *AuthStorage_GetUserByEmail_Call {
	return &AuthStorage_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *AuthStorage_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *AuthStorage_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthStorage_GetUserByEmail_Call) Return(user *models.User, err error) *AuthStorage_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthStorage_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *AuthStorage_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionStorage creates a new instance of SessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStorage {
	mock := &SessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionStorage is an autogenerated mock type for the SessionStorage type
type SessionStorage struct {
	mock.Mock
}

type SessionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionStorage) EXPECT() *SessionStorage_Expecter {
	return &SessionStorage_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type SessionStorage
func (_mock *SessionStorage) CreateSession(ctx context.Context, userID uint64, refreshHash []byte, expiresAt time.Time, userAgent string, ip string) error {
	ret := _mock.Called(ctx, userID, refreshHash, expiresAt, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte, time.Time, string, string) error); ok {
		r0 = returnFunc(ctx, userID, refreshHash, expiresAt, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionStorage_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionStorage_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - refreshHash []byte
//   - expiresAt time.Time
//   - userAgent string
//   - ip string
func (_e *SessionStorage_Expecter) CreateSession(ctx interface{}, userID interface{}, refreshHash interface{}, expiresAt interface{}, userAgent interface{}, ip interface{}) *SessionStorage_CreateSession_Call {
	return &SessionStorage_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, refreshHash, expiresAt, userAgent, ip)}
}

func (_c *SessionStorage_CreateSession_Call) Run(run func(ctx context.Context, userID uint64, refreshHash []byte, expiresAt time.Time, userAgent string, ip string)) *SessionStorage_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *SessionStorage_CreateSession_Call) Return(err error) *SessionStorage_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionStorage_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID uint64, refreshHash []byte, expiresAt time.Time, userAgent string, ip string) error) *SessionStorage_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshHash provides a mock function for the type SessionStorage
func (_mock *SessionStorage) GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (*models.Session, error) {
	ret := _mock.Called(ctx, refreshHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshHash")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*models.Session, error)); ok {
		return returnFunc(ctx, refreshHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *models.Session); ok {
		r0 = returnFunc(ctx, refreshHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, refreshHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionStorage_GetSessionByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshHash'
type SessionStorage_GetSessionByRefreshHash_Call struct {
	*mock.Call
}

// GetSessionByRefreshHash is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshHash []byte
func (_e *SessionStorage_Expecter) GetSessionByRefreshHash(ctx interface{}, refreshHash interface{}) *SessionStorage_GetSessionByRefreshHash_Call {
	return &SessionStorage_GetSessionByRefreshHash_Call{Call: _e.mock.On("GetSessionByRefreshHash", ctx, refreshHash)}
}

func (_c *SessionStorage_GetSessionByRefreshHash_Call) Run(run func(ctx context.Context, refreshHash []byte)) *SessionStorage_GetSessionByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStorage_GetSessionByRefreshHash_Call) Return(session *models.Session, err error) *SessionStorage_GetSessionByRefreshHash_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionStorage_GetSessionByRefreshHash_Call) RunAndReturn(run func(ctx context.Context, refreshHash []byte) (*models.Session, error)) *SessionStorage_GetSessionByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessionsByUserID provides a mock function for the type SessionStorage
func (_mock *SessionStorage) RevokeAllSessionsByUserID(ctx context.Context, userID uint64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessionsByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionStorage_RevokeAllSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessionsByUserID'
type SessionStorage_RevokeAllSessionsByUserID_Call struct {
	*mock.Call
}

// RevokeAllSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *SessionStorage_Expecter) RevokeAllSessionsByUserID(ctx interface{}, userID interface{}) *SessionStorage_RevokeAllSessionsByUserID_Call {
	return &SessionStorage_RevokeAllSessionsByUserID_Call{Call: _e.mock.On("RevokeAllSessionsByUserID", ctx, userID)}
}

func (_c *SessionStorage_RevokeAllSessionsByUserID_Call) Run(run func(ctx context.Context, userID uint64)) *SessionStorage_RevokeAllSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStorage_RevokeAllSessionsByUserID_Call) Return(err error) *SessionStorage_RevokeAllSessionsByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionStorage_RevokeAllSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) error) *SessionStorage_RevokeAllSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSessionByRefreshHash provides a mock function for the type SessionStorage
func (_mock *SessionStorage) RevokeSessionByRefreshHash(ctx context.Context, refreshHash []byte) error {
	ret := _mock.Called(ctx, refreshHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionByRefreshHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, refreshHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionStorage_RevokeSessionByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionByRefreshHash'
type SessionStorage_RevokeSessionByRefreshHash_Call struct {
	*mock.Call
}

// RevokeSessionByRefreshHash is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshHash []byte
func (_e *SessionStorage_Expecter) RevokeSessionByRefreshHash(ctx interface{}, refreshHash interface{}) *SessionStorage_RevokeSessionByRefreshHash_Call {
	return &SessionStorage_RevokeSessionByRefreshHash_Call{Call: _e.mock.On("RevokeSessionByRefreshHash", ctx, refreshHash)}
}

func (_c *SessionStorage_RevokeSessionByRefreshHash_Call) Run(run func(ctx context.Context, refreshHash []byte)) *SessionStorage_RevokeSessionByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStorage_RevokeSessionByRefreshHash_Call) Return(err error) *SessionStorage_RevokeSessionByRefreshHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionStorage_RevokeSessionByRefreshHash_Call) RunAndReturn(run func(ctx context.Context, refreshHash []byte) error) *SessionStorage_RevokeSessionByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}
