// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: library_api/library.proto

package library_api

import (
	models "github.com/vbncursed/medialog/library_service/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_library_api_library_proto protoreflect.FileDescriptor

const file_library_api_library_proto_rawDesc = "" +
	"\n" +
	"\x19library_api/library.proto\x12\x12library.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1amodels/library_model.proto2\x91\x05\n" +
	"\x0eLibraryService\x12v\n" +
	"\vCreateEntry\x12%.library.models.v1.CreateEntryRequest\x1a .library.models.v1.EntryResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/library/entries\x12x\n" +
	"\bGetEntry\x12\".library.models.v1.GetEntryRequest\x1a .library.models.v1.EntryResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/library/entries/{entry_id}\x12\x81\x01\n" +
	"\vUpdateEntry\x12%.library.models.v1.UpdateEntryRequest\x1a .library.models.v1.EntryResponse\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/v1/library/entries/{entry_id}\x12\x84\x01\n" +
	"\vDeleteEntry\x12%.library.models.v1.DeleteEntryRequest\x1a&.library.models.v1.DeleteEntryResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/library/entries/{entry_id}\x12\x81\x01\n" +
	"\vListEntries\x12%.library.models.v1.ListEntriesRequest\x1a&.library.models.v1.ListEntriesResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/library/entries/listBGZEgithub.com/vbncursed/medialog/library_service/internal/pb/library_apib\x06proto3"

var file_library_api_library_proto_goTypes = []any{
	(*models.CreateEntryRequest)(nil),  // 0: library.models.v1.CreateEntryRequest
	(*models.GetEntryRequest)(nil),     // 1: library.models.v1.GetEntryRequest
	(*models.UpdateEntryRequest)(nil),  // 2: library.models.v1.UpdateEntryRequest
	(*models.DeleteEntryRequest)(nil),  // 3: library.models.v1.DeleteEntryRequest
	(*models.ListEntriesRequest)(nil),  // 4: library.models.v1.ListEntriesRequest
	(*models.EntryResponse)(nil),       // 5: library.models.v1.EntryResponse
	(*models.DeleteEntryResponse)(nil), // 6: library.models.v1.DeleteEntryResponse
	(*models.ListEntriesResponse)(nil), // 7: library.models.v1.ListEntriesResponse
}
var file_library_api_library_proto_depIdxs = []int32{
	0, // 0: library.service.v1.LibraryService.CreateEntry:input_type -> library.models.v1.CreateEntryRequest
	1, // 1: library.service.v1.LibraryService.GetEntry:input_type -> library.models.v1.GetEntryRequest
	2, // 2: library.service.v1.LibraryService.UpdateEntry:input_type -> library.models.v1.UpdateEntryRequest
	3, // 3: library.service.v1.LibraryService.DeleteEntry:input_type -> library.models.v1.DeleteEntryRequest
	4, // 4: library.service.v1.LibraryService.ListEntries:input_type -> library.models.v1.ListEntriesRequest
	5, // 5: library.service.v1.LibraryService.CreateEntry:output_type -> library.models.v1.EntryResponse
	5, // 6: library.service.v1.LibraryService.GetEntry:output_type -> library.models.v1.EntryResponse
	5, // 7: library.service.v1.LibraryService.UpdateEntry:output_type -> library.models.v1.EntryResponse
	6, // 8: library.service.v1.LibraryService.DeleteEntry:output_type -> library.models.v1.DeleteEntryResponse
	7, // 9: library.service.v1.LibraryService.ListEntries:output_type -> library.models.v1.ListEntriesResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_library_api_library_proto_init() }
func file_library_api_library_proto_init() {
	if File_library_api_library_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_library_api_library_proto_rawDesc), len(file_library_api_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_library_api_library_proto_goTypes,
		DependencyIndexes: file_library_api_library_proto_depIdxs,
	}.Build()
	File_library_api_library_proto = out.File
	file_library_api_library_proto_goTypes = nil
	file_library_api_library_proto_depIdxs = nil
}
