// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: library_api/library.proto

package library_api

import (
	context "context"
	models "github.com/vbncursed/medialog/library_service/internal/pb/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LibraryService_CreateEntry_FullMethodName = "/library.service.v1.LibraryService/CreateEntry"
	LibraryService_GetEntry_FullMethodName    = "/library.service.v1.LibraryService/GetEntry"
	LibraryService_UpdateEntry_FullMethodName = "/library.service.v1.LibraryService/UpdateEntry"
	LibraryService_DeleteEntry_FullMethodName = "/library.service.v1.LibraryService/DeleteEntry"
	LibraryService_ListEntries_FullMethodName = "/library.service.v1.LibraryService/ListEntries"
)

// LibraryServiceClient is the client API for LibraryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LibraryService предоставляет операции управления библиотекой пользователя (записями о контенте).
type LibraryServiceClient interface {
	// CreateEntry создаёт новую запись в библиотеке пользователя.
	CreateEntry(ctx context.Context, in *models.CreateEntryRequest, opts ...grpc.CallOption) (*models.EntryResponse, error)
	// GetEntry возвращает запись по ID (с проверкой владельца).
	// user_id извлекается из токена авторизации.
	GetEntry(ctx context.Context, in *models.GetEntryRequest, opts ...grpc.CallOption) (*models.EntryResponse, error)
	// UpdateEntry обновляет существующую запись (статус, оценка, заметка, теги, даты).
	UpdateEntry(ctx context.Context, in *models.UpdateEntryRequest, opts ...grpc.CallOption) (*models.EntryResponse, error)
	// DeleteEntry удаляет запись из библиотеки пользователя.
	// user_id извлекается из токена авторизации.
	DeleteEntry(ctx context.Context, in *models.DeleteEntryRequest, opts ...grpc.CallOption) (*models.DeleteEntryResponse, error)
	// ListEntries возвращает список записей с фильтрацией, сортировкой и пагинацией.
	ListEntries(ctx context.Context, in *models.ListEntriesRequest, opts ...grpc.CallOption) (*models.ListEntriesResponse, error)
}

type libraryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLibraryServiceClient(cc grpc.ClientConnInterface) LibraryServiceClient {
	return &libraryServiceClient{cc}
}

func (c *libraryServiceClient) CreateEntry(ctx context.Context, in *models.CreateEntryRequest, opts ...grpc.CallOption) (*models.EntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.EntryResponse)
	err := c.cc.Invoke(ctx, LibraryService_CreateEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) GetEntry(ctx context.Context, in *models.GetEntryRequest, opts ...grpc.CallOption) (*models.EntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.EntryResponse)
	err := c.cc.Invoke(ctx, LibraryService_GetEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) UpdateEntry(ctx context.Context, in *models.UpdateEntryRequest, opts ...grpc.CallOption) (*models.EntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.EntryResponse)
	err := c.cc.Invoke(ctx, LibraryService_UpdateEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) DeleteEntry(ctx context.Context, in *models.DeleteEntryRequest, opts ...grpc.CallOption) (*models.DeleteEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.DeleteEntryResponse)
	err := c.cc.Invoke(ctx, LibraryService_DeleteEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) ListEntries(ctx context.Context, in *models.ListEntriesRequest, opts ...grpc.CallOption) (*models.ListEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ListEntriesResponse)
	err := c.cc.Invoke(ctx, LibraryService_ListEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServiceServer is the server API for LibraryService service.
// All implementations must embed UnimplementedLibraryServiceServer
// for forward compatibility.
//
// LibraryService предоставляет операции управления библиотекой пользователя (записями о контенте).
type LibraryServiceServer interface {
	// CreateEntry создаёт новую запись в библиотеке пользователя.
	CreateEntry(context.Context, *models.CreateEntryRequest) (*models.EntryResponse, error)
	// GetEntry возвращает запись по ID (с проверкой владельца).
	// user_id извлекается из токена авторизации.
	GetEntry(context.Context, *models.GetEntryRequest) (*models.EntryResponse, error)
	// UpdateEntry обновляет существующую запись (статус, оценка, заметка, теги, даты).
	UpdateEntry(context.Context, *models.UpdateEntryRequest) (*models.EntryResponse, error)
	// DeleteEntry удаляет запись из библиотеки пользователя.
	// user_id извлекается из токена авторизации.
	DeleteEntry(context.Context, *models.DeleteEntryRequest) (*models.DeleteEntryResponse, error)
	// ListEntries возвращает список записей с фильтрацией, сортировкой и пагинацией.
	ListEntries(context.Context, *models.ListEntriesRequest) (*models.ListEntriesResponse, error)
	mustEmbedUnimplementedLibraryServiceServer()
}

// UnimplementedLibraryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLibraryServiceServer struct{}

func (UnimplementedLibraryServiceServer) CreateEntry(context.Context, *models.CreateEntryRequest) (*models.EntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEntry not implemented")
}
func (UnimplementedLibraryServiceServer) GetEntry(context.Context, *models.GetEntryRequest) (*models.EntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedLibraryServiceServer) UpdateEntry(context.Context, *models.UpdateEntryRequest) (*models.EntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEntry not implemented")
}
func (UnimplementedLibraryServiceServer) DeleteEntry(context.Context, *models.DeleteEntryRequest) (*models.DeleteEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEntry not implemented")
}
func (UnimplementedLibraryServiceServer) ListEntries(context.Context, *models.ListEntriesRequest) (*models.ListEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntries not implemented")
}
func (UnimplementedLibraryServiceServer) mustEmbedUnimplementedLibraryServiceServer() {}
func (UnimplementedLibraryServiceServer) testEmbeddedByValue()                        {}

// UnsafeLibraryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LibraryServiceServer will
// result in compilation errors.
type UnsafeLibraryServiceServer interface {
	mustEmbedUnimplementedLibraryServiceServer()
}

func RegisterLibraryServiceServer(s grpc.ServiceRegistrar, srv LibraryServiceServer) {
	// If the following call panics, it indicates UnimplementedLibraryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LibraryService_ServiceDesc, srv)
}

func _LibraryService_CreateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).CreateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibraryService_CreateEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).CreateEntry(ctx, req.(*models.CreateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibraryService_GetEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).GetEntry(ctx, req.(*models.GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibraryService_UpdateEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).UpdateEntry(ctx, req.(*models.UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_DeleteEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.DeleteEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).DeleteEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibraryService_DeleteEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).DeleteEntry(ctx, req.(*models.DeleteEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibraryService_ListEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).ListEntries(ctx, req.(*models.ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LibraryService_ServiceDesc is the grpc.ServiceDesc for LibraryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LibraryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "library.service.v1.LibraryService",
	HandlerType: (*LibraryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntry",
			Handler:    _LibraryService_CreateEntry_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _LibraryService_GetEntry_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _LibraryService_UpdateEntry_Handler,
		},
		{
			MethodName: "DeleteEntry",
			Handler:    _LibraryService_DeleteEntry_Handler,
		},
		{
			MethodName: "ListEntries",
			Handler:    _LibraryService_ListEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "library_api/library.proto",
}
