// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: metadata_api/metadata.proto

package metadata_api

import (
	context "context"
	models "github.com/vbncursed/medialog/metadata_service/internal/pb/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_SearchMedia_FullMethodName          = "/metadata.service.v1.MetadataService/SearchMedia"
	MetadataService_GetMedia_FullMethodName             = "/metadata.service.v1.MetadataService/GetMedia"
	MetadataService_GetMediaByExternalID_FullMethodName = "/metadata.service.v1.MetadataService/GetMediaByExternalID"
	MetadataService_CreateMedia_FullMethodName          = "/metadata.service.v1.MetadataService/CreateMedia"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataService предоставляет операции поиска и получения метаданных контента.
type MetadataServiceClient interface {
	// SearchMedia выполняет поиск контента по названию и опционально по внешним ID.
	SearchMedia(ctx context.Context, in *models.SearchMediaRequest, opts ...grpc.CallOption) (*models.SearchMediaResponse, error)
	// GetMedia возвращает карточку контента по media_id.
	GetMedia(ctx context.Context, in *models.GetMediaRequest, opts ...grpc.CallOption) (*models.GetMediaResponse, error)
	// GetMediaByExternalID возвращает контент по внешнему ID (tmdb_id, isbn и т.д.).
	GetMediaByExternalID(ctx context.Context, in *models.GetMediaByExternalIDRequest, opts ...grpc.CallOption) (*models.GetMediaResponse, error)
	// CreateMedia создаёт новую запись media с минимальными данными (если контент не найден).
	CreateMedia(ctx context.Context, in *models.CreateMediaRequest, opts ...grpc.CallOption) (*models.GetMediaResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) SearchMedia(ctx context.Context, in *models.SearchMediaRequest, opts ...grpc.CallOption) (*models.SearchMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.SearchMediaResponse)
	err := c.cc.Invoke(ctx, MetadataService_SearchMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetMedia(ctx context.Context, in *models.GetMediaRequest, opts ...grpc.CallOption) (*models.GetMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.GetMediaResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetMediaByExternalID(ctx context.Context, in *models.GetMediaByExternalIDRequest, opts ...grpc.CallOption) (*models.GetMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.GetMediaResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetMediaByExternalID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateMedia(ctx context.Context, in *models.CreateMediaRequest, opts ...grpc.CallOption) (*models.GetMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.GetMediaResponse)
	err := c.cc.Invoke(ctx, MetadataService_CreateMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
//
// MetadataService предоставляет операции поиска и получения метаданных контента.
type MetadataServiceServer interface {
	// SearchMedia выполняет поиск контента по названию и опционально по внешним ID.
	SearchMedia(context.Context, *models.SearchMediaRequest) (*models.SearchMediaResponse, error)
	// GetMedia возвращает карточку контента по media_id.
	GetMedia(context.Context, *models.GetMediaRequest) (*models.GetMediaResponse, error)
	// GetMediaByExternalID возвращает контент по внешнему ID (tmdb_id, isbn и т.д.).
	GetMediaByExternalID(context.Context, *models.GetMediaByExternalIDRequest) (*models.GetMediaResponse, error)
	// CreateMedia создаёт новую запись media с минимальными данными (если контент не найден).
	CreateMedia(context.Context, *models.CreateMediaRequest) (*models.GetMediaResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) SearchMedia(context.Context, *models.SearchMediaRequest) (*models.SearchMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMedia not implemented")
}
func (UnimplementedMetadataServiceServer) GetMedia(context.Context, *models.GetMediaRequest) (*models.GetMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedMetadataServiceServer) GetMediaByExternalID(context.Context, *models.GetMediaByExternalIDRequest) (*models.GetMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMediaByExternalID not implemented")
}
func (UnimplementedMetadataServiceServer) CreateMedia(context.Context, *models.CreateMediaRequest) (*models.GetMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMedia not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_SearchMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.SearchMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SearchMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_SearchMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SearchMedia(ctx, req.(*models.SearchMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GetMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMedia(ctx, req.(*models.GetMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetMediaByExternalID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GetMediaByExternalIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMediaByExternalID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetMediaByExternalID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMediaByExternalID(ctx, req.(*models.GetMediaByExternalIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreateMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_CreateMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateMedia(ctx, req.(*models.CreateMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.service.v1.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMedia",
			Handler:    _MetadataService_SearchMedia_Handler,
		},
		{
			MethodName: "GetMedia",
			Handler:    _MetadataService_GetMedia_Handler,
		},
		{
			MethodName: "GetMediaByExternalID",
			Handler:    _MetadataService_GetMediaByExternalID_Handler,
		},
		{
			MethodName: "CreateMedia",
			Handler:    _MetadataService_CreateMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata_api/metadata.proto",
}
