// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/metadata_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_MOVIE       MediaType = 1
	MediaType_MEDIA_TYPE_TV          MediaType = 2
	MediaType_MEDIA_TYPE_BOOK        MediaType = 3
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_MOVIE",
		2: "MEDIA_TYPE_TV",
		3: "MEDIA_TYPE_BOOK",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_MOVIE":       1,
		"MEDIA_TYPE_TV":          2,
		"MEDIA_TYPE_BOOK":        3,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_metadata_model_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_models_metadata_model_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{0}
}

type ExternalID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // tmdb, imdb, isbn, etc.
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalID) Reset() {
	*x = ExternalID{}
	mi := &file_models_metadata_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalID) ProtoMessage() {}

func (x *ExternalID) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalID.ProtoReflect.Descriptor instead.
func (*ExternalID) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalID) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExternalID) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint64                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Type          MediaType              `protobuf:"varint,2,opt,name=type,proto3,enum=metadata.models.v1.MediaType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year          *uint32                `protobuf:"varint,4,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	PosterUrl     *string                `protobuf:"bytes,6,opt,name=poster_url,json=posterUrl,proto3,oneof" json:"poster_url,omitempty"` // для фильмов/сериалов
	CoverUrl      *string                `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"`    // для книг
	ExternalIds   []*ExternalID          `protobuf:"bytes,8,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_models_metadata_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{1}
}

func (x *Media) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *Media) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *Media) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Media) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Media) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Media) GetPosterUrl() string {
	if x != nil && x.PosterUrl != nil {
		return *x.PosterUrl
	}
	return ""
}

func (x *Media) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

func (x *Media) GetExternalIds() []*ExternalID {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *Media) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SearchMediaRequest - запрос на поиск контента
type SearchMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                        // поисковый запрос (название)
	Type          *MediaType             `protobuf:"varint,2,opt,name=type,proto3,enum=metadata.models.v1.MediaType,oneof" json:"type,omitempty"` // фильтр по типу (опционально)
	ExternalId    *ExternalID            `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`      // поиск по внешнему ID (опционально)
	Page          uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                                         // номер страницы (начинается с 1)
	PageSize      uint32                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                 // размер страницы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMediaRequest) Reset() {
	*x = SearchMediaRequest{}
	mi := &file_models_metadata_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMediaRequest) ProtoMessage() {}

func (x *SearchMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMediaRequest.ProtoReflect.Descriptor instead.
func (*SearchMediaRequest) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMediaRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMediaRequest) GetType() MediaType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *SearchMediaRequest) GetExternalId() *ExternalID {
	if x != nil {
		return x.ExternalId
	}
	return nil
}

func (x *SearchMediaRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMediaRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// SearchMediaResponse - результат поиска
type SearchMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Media               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMediaResponse) Reset() {
	*x = SearchMediaResponse{}
	mi := &file_models_metadata_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMediaResponse) ProtoMessage() {}

func (x *SearchMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMediaResponse.ProtoReflect.Descriptor instead.
func (*SearchMediaResponse) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMediaResponse) GetResults() []*Media {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchMediaResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchMediaResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMediaResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchMediaResponse) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// GetMediaRequest - запрос на получение контента по ID
type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint64                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_models_metadata_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetMediaRequest) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

// GetMediaResponse - ответ с данными контента
type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_models_metadata_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

// GetMediaByExternalIDRequest - запрос на получение контента по внешнему ID
type GetMediaByExternalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // tmdb, imdb, isbn и т.д.
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByExternalIDRequest) Reset() {
	*x = GetMediaByExternalIDRequest{}
	mi := &file_models_metadata_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByExternalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByExternalIDRequest) ProtoMessage() {}

func (x *GetMediaByExternalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByExternalIDRequest.ProtoReflect.Descriptor instead.
func (*GetMediaByExternalIDRequest) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaByExternalIDRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetMediaByExternalIDRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// CreateMediaRequest - запрос на создание новой записи media
type CreateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=metadata.models.v1.MediaType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          *uint32                `protobuf:"varint,3,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	PosterUrl     *string                `protobuf:"bytes,5,opt,name=poster_url,json=posterUrl,proto3,oneof" json:"poster_url,omitempty"`
	CoverUrl      *string                `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"`
	ExternalIds   []*ExternalID          `protobuf:"bytes,7,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaRequest) Reset() {
	*x = CreateMediaRequest{}
	mi := &file_models_metadata_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaRequest) ProtoMessage() {}

func (x *CreateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_metadata_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaRequest.ProtoReflect.Descriptor instead.
func (*CreateMediaRequest) Descriptor() ([]byte, []int) {
	return file_models_metadata_model_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMediaRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *CreateMediaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMediaRequest) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *CreateMediaRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *CreateMediaRequest) GetPosterUrl() string {
	if x != nil && x.PosterUrl != nil {
		return *x.PosterUrl
	}
	return ""
}

func (x *CreateMediaRequest) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

func (x *CreateMediaRequest) GetExternalIds() []*ExternalID {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

var File_models_metadata_model_proto protoreflect.FileDescriptor

const file_models_metadata_model_proto_rawDesc = "" +
	"\n" +
	"\x1bmodels/metadata_model.proto\x12\x12metadata.models.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\n" +
	"ExternalID\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"\x86\x03\n" +
	"\x05Media\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x04R\amediaId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.metadata.models.v1.MediaTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\x04year\x18\x04 \x01(\rH\x00R\x04year\x88\x01\x01\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12\"\n" +
	"\n" +
	"poster_url\x18\x06 \x01(\tH\x01R\tposterUrl\x88\x01\x01\x12 \n" +
	"\tcover_url\x18\a \x01(\tH\x02R\bcoverUrl\x88\x01\x01\x12A\n" +
	"\fexternal_ids\x18\b \x03(\v2\x1e.metadata.models.v1.ExternalIDR\vexternalIds\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\a\n" +
	"\x05_yearB\r\n" +
	"\v_poster_urlB\f\n" +
	"\n" +
	"_cover_url\"\xf2\x01\n" +
	"\x12SearchMediaRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.metadata.models.v1.MediaTypeH\x00R\x04type\x88\x01\x01\x12D\n" +
	"\vexternal_id\x18\x03 \x01(\v2\x1e.metadata.models.v1.ExternalIDH\x01R\n" +
	"externalId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x04 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\rR\bpageSizeB\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_external_id\"\xb2\x01\n" +
	"\x13SearchMediaResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.metadata.models.v1.MediaR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\rR\n" +
	"totalPages\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x04R\amediaId\"C\n" +
	"\x10GetMediaResponse\x12/\n" +
	"\x05media\x18\x01 \x01(\v2\x19.metadata.models.v1.MediaR\x05media\"V\n" +
	"\x1bGetMediaByExternalIDRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"\xbd\x02\n" +
	"\x12CreateMediaRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.metadata.models.v1.MediaTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\x04year\x18\x03 \x01(\rH\x00R\x04year\x88\x01\x01\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\"\n" +
	"\n" +
	"poster_url\x18\x05 \x01(\tH\x01R\tposterUrl\x88\x01\x01\x12 \n" +
	"\tcover_url\x18\x06 \x01(\tH\x02R\bcoverUrl\x88\x01\x01\x12A\n" +
	"\fexternal_ids\x18\a \x03(\v2\x1e.metadata.models.v1.ExternalIDR\vexternalIdsB\a\n" +
	"\x05_yearB\r\n" +
	"\v_poster_urlB\f\n" +
	"\n" +
	"_cover_url*e\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_MOVIE\x10\x01\x12\x11\n" +
	"\rMEDIA_TYPE_TV\x10\x02\x12\x13\n" +
	"\x0fMEDIA_TYPE_BOOK\x10\x03BCZAgithub.com/vbncursed/medialog/metadata_service/internal/pb/modelsb\x06proto3"

var (
	file_models_metadata_model_proto_rawDescOnce sync.Once
	file_models_metadata_model_proto_rawDescData []byte
)

func file_models_metadata_model_proto_rawDescGZIP() []byte {
	file_models_metadata_model_proto_rawDescOnce.Do(func() {
		file_models_metadata_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_metadata_model_proto_rawDesc), len(file_models_metadata_model_proto_rawDesc)))
	})
	return file_models_metadata_model_proto_rawDescData
}

var file_models_metadata_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_metadata_model_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_models_metadata_model_proto_goTypes = []any{
	(MediaType)(0),                      // 0: metadata.models.v1.MediaType
	(*ExternalID)(nil),                  // 1: metadata.models.v1.ExternalID
	(*Media)(nil),                       // 2: metadata.models.v1.Media
	(*SearchMediaRequest)(nil),          // 3: metadata.models.v1.SearchMediaRequest
	(*SearchMediaResponse)(nil),         // 4: metadata.models.v1.SearchMediaResponse
	(*GetMediaRequest)(nil),             // 5: metadata.models.v1.GetMediaRequest
	(*GetMediaResponse)(nil),            // 6: metadata.models.v1.GetMediaResponse
	(*GetMediaByExternalIDRequest)(nil), // 7: metadata.models.v1.GetMediaByExternalIDRequest
	(*CreateMediaRequest)(nil),          // 8: metadata.models.v1.CreateMediaRequest
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_models_metadata_model_proto_depIdxs = []int32{
	0, // 0: metadata.models.v1.Media.type:type_name -> metadata.models.v1.MediaType
	1, // 1: metadata.models.v1.Media.external_ids:type_name -> metadata.models.v1.ExternalID
	9, // 2: metadata.models.v1.Media.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: metadata.models.v1.SearchMediaRequest.type:type_name -> metadata.models.v1.MediaType
	1, // 4: metadata.models.v1.SearchMediaRequest.external_id:type_name -> metadata.models.v1.ExternalID
	2, // 5: metadata.models.v1.SearchMediaResponse.results:type_name -> metadata.models.v1.Media
	2, // 6: metadata.models.v1.GetMediaResponse.media:type_name -> metadata.models.v1.Media
	0, // 7: metadata.models.v1.CreateMediaRequest.type:type_name -> metadata.models.v1.MediaType
	1, // 8: metadata.models.v1.CreateMediaRequest.external_ids:type_name -> metadata.models.v1.ExternalID
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_models_metadata_model_proto_init() }
func file_models_metadata_model_proto_init() {
	if File_models_metadata_model_proto != nil {
		return
	}
	file_models_metadata_model_proto_msgTypes[1].OneofWrappers = []any{}
	file_models_metadata_model_proto_msgTypes[2].OneofWrappers = []any{}
	file_models_metadata_model_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_metadata_model_proto_rawDesc), len(file_models_metadata_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_metadata_model_proto_goTypes,
		DependencyIndexes: file_models_metadata_model_proto_depIdxs,
		EnumInfos:         file_models_metadata_model_proto_enumTypes,
		MessageInfos:      file_models_metadata_model_proto_msgTypes,
	}.Build()
	File_models_metadata_model_proto = out.File
	file_models_metadata_model_proto_goTypes = nil
	file_models_metadata_model_proto_depIdxs = nil
}
