// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vbncursed/medialog/auth-service/internal/services/authService"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type Service
func (_mock *Service) Login(ctx context.Context, email string, password string, userAgent string, ip string) (*authService.AuthResult, error) {
	ret := _mock.Called(ctx, email, password, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authService.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*authService.AuthResult, error)); ok {
		return returnFunc(ctx, email, password, userAgent, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *authService.AuthResult); ok {
		r0 = returnFunc(ctx, email, password, userAgent, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authService.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - userAgent string
//   - ip string
func (_e *Service_Expecter) Login(ctx interface{}, email interface{}, password interface{}, userAgent interface{}, ip interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", ctx, email, password, userAgent, ip)}
}

func (_c *Service_Login_Call) Run(run func(ctx context.Context, email string, password string, userAgent string, ip string)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Service_Login_Call) Return(authResult *authService.AuthResult, err error) *Service_Login_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string, userAgent string, ip string) (*authService.AuthResult, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type Service
func (_mock *Service) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type Service_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Service_Expecter) Logout(ctx interface{}, refreshToken interface{}) *Service_Logout_Call {
	return &Service_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *Service_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *Service_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Logout_Call) Return(err error) *Service_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *Service_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function for the type Service
func (_mock *Service) LogoutAll(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type Service_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Service_Expecter) LogoutAll(ctx interface{}, refreshToken interface{}) *Service_LogoutAll_Call {
	return &Service_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, refreshToken)}
}

func (_c *Service_LogoutAll_Call) Run(run func(ctx context.Context, refreshToken string)) *Service_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_LogoutAll_Call) Return(err error) *Service_LogoutAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_LogoutAll_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *Service_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type Service
func (_mock *Service) Refresh(ctx context.Context, refreshToken string, userAgent string, ip string) (*authService.AuthResult, error) {
	ret := _mock.Called(ctx, refreshToken, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *authService.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*authService.AuthResult, error)); ok {
		return returnFunc(ctx, refreshToken, userAgent, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *authService.AuthResult); ok {
		r0 = returnFunc(ctx, refreshToken, userAgent, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authService.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, refreshToken, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type Service_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - userAgent string
//   - ip string
func (_e *Service_Expecter) Refresh(ctx interface{}, refreshToken interface{}, userAgent interface{}, ip interface{}) *Service_Refresh_Call {
	return &Service_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken, userAgent, ip)}
}

func (_c *Service_Refresh_Call) Run(run func(ctx context.Context, refreshToken string, userAgent string, ip string)) *Service_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_Refresh_Call) Return(authResult *authService.AuthResult, err error) *Service_Refresh_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *Service_Refresh_Call) RunAndReturn(run func(ctx context.Context, refreshToken string, userAgent string, ip string) (*authService.AuthResult, error)) *Service_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Service
func (_mock *Service) Register(ctx context.Context, email string, password string, userAgent string, ip string) (*authService.AuthResult, error) {
	ret := _mock.Called(ctx, email, password, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authService.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*authService.AuthResult, error)); ok {
		return returnFunc(ctx, email, password, userAgent, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *authService.AuthResult); ok {
		r0 = returnFunc(ctx, email, password, userAgent, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authService.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Service_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - userAgent string
//   - ip string
func (_e *Service_Expecter) Register(ctx interface{}, email interface{}, password interface{}, userAgent interface{}, ip interface{}) *Service_Register_Call {
	return &Service_Register_Call{Call: _e.mock.On("Register", ctx, email, password, userAgent, ip)}
}

func (_c *Service_Register_Call) Run(run func(ctx context.Context, email string, password string, userAgent string, ip string)) *Service_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Service_Register_Call) Return(authResult *authService.AuthResult, err error) *Service_Register_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *Service_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string, userAgent string, ip string) (*authService.AuthResult, error)) *Service_Register_Call {
	_c.Call.Return(run)
	return _c
}
