// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/vbncursed/medialog/auth-service/internal/models"
	"github.com/vbncursed/medialog/auth-service/internal/services/authService"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type Service
func (_mock *Service) Login(ctx context.Context, in models.LoginInput) (*authService.AuthInfo, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authService.AuthInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LoginInput) (*authService.AuthInfo, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LoginInput) *authService.AuthInfo); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authService.AuthInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.LoginInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.LoginInput
func (_e *Service_Expecter) Login(ctx interface{}, in interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", ctx, in)}
}

func (_c *Service_Login_Call) Run(run func(ctx context.Context, in models.LoginInput)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.LoginInput
		if args[1] != nil {
			arg1 = args[1].(models.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Login_Call) Return(authInfo *authService.AuthInfo, err error) *Service_Login_Call {
	_c.Call.Return(authInfo, err)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(ctx context.Context, in models.LoginInput) (*authService.AuthInfo, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type Service
func (_mock *Service) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type Service_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Service_Expecter) Logout(ctx interface{}, refreshToken interface{}) *Service_Logout_Call {
	return &Service_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *Service_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *Service_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Logout_Call) Return(err error) *Service_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *Service_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function for the type Service
func (_mock *Service) LogoutAll(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type Service_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Service_Expecter) LogoutAll(ctx interface{}, refreshToken interface{}) *Service_LogoutAll_Call {
	return &Service_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, refreshToken)}
}

func (_c *Service_LogoutAll_Call) Run(run func(ctx context.Context, refreshToken string)) *Service_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_LogoutAll_Call) Return(err error) *Service_LogoutAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_LogoutAll_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *Service_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type Service
func (_mock *Service) Refresh(ctx context.Context, in models.RefreshInput) (*authService.AuthInfo, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *authService.AuthInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.RefreshInput) (*authService.AuthInfo, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.RefreshInput) *authService.AuthInfo); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authService.AuthInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.RefreshInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type Service_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.RefreshInput
func (_e *Service_Expecter) Refresh(ctx interface{}, in interface{}) *Service_Refresh_Call {
	return &Service_Refresh_Call{Call: _e.mock.On("Refresh", ctx, in)}
}

func (_c *Service_Refresh_Call) Run(run func(ctx context.Context, in models.RefreshInput)) *Service_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.RefreshInput
		if args[1] != nil {
			arg1 = args[1].(models.RefreshInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Refresh_Call) Return(authInfo *authService.AuthInfo, err error) *Service_Refresh_Call {
	_c.Call.Return(authInfo, err)
	return _c
}

func (_c *Service_Refresh_Call) RunAndReturn(run func(ctx context.Context, in models.RefreshInput) (*authService.AuthInfo, error)) *Service_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Service
func (_mock *Service) Register(ctx context.Context, in models.RegisterInput) (*authService.AuthInfo, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authService.AuthInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.RegisterInput) (*authService.AuthInfo, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.RegisterInput) *authService.AuthInfo); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authService.AuthInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.RegisterInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Service_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.RegisterInput
func (_e *Service_Expecter) Register(ctx interface{}, in interface{}) *Service_Register_Call {
	return &Service_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *Service_Register_Call) Run(run func(ctx context.Context, in models.RegisterInput)) *Service_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(models.RegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Register_Call) Return(authInfo *authService.AuthInfo, err error) *Service_Register_Call {
	_c.Call.Return(authInfo, err)
	return _c
}

func (_c *Service_Register_Call) RunAndReturn(run func(ctx context.Context, in models.RegisterInput) (*authService.AuthInfo, error)) *Service_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type Storage
func (_mock *Storage) CreateSession(ctx context.Context, userID uint64, refreshHash []byte, expiresAt time.Time, userAgent string, ip string) (uint64, error) {
	ret := _mock.Called(ctx, userID, refreshHash, expiresAt, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte, time.Time, string, string) (uint64, error)); ok {
		return returnFunc(ctx, userID, refreshHash, expiresAt, userAgent, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte, time.Time, string, string) uint64); ok {
		r0 = returnFunc(ctx, userID, refreshHash, expiresAt, userAgent, ip)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, []byte, time.Time, string, string) error); ok {
		r1 = returnFunc(ctx, userID, refreshHash, expiresAt, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type Storage_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - refreshHash []byte
//   - expiresAt time.Time
//   - userAgent string
//   - ip string
func (_e *Storage_Expecter) CreateSession(ctx interface{}, userID interface{}, refreshHash interface{}, expiresAt interface{}, userAgent interface{}, ip interface{}) *Storage_CreateSession_Call {
	return &Storage_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, refreshHash, expiresAt, userAgent, ip)}
}

func (_c *Storage_CreateSession_Call) Run(run func(ctx context.Context, userID uint64, refreshHash []byte, expiresAt time.Time, userAgent string, ip string)) *Storage_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Storage_CreateSession_Call) Return(v uint64, err error) *Storage_CreateSession_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Storage_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID uint64, refreshHash []byte, expiresAt time.Time, userAgent string, ip string) (uint64, error)) *Storage_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type Storage
func (_mock *Storage) CreateUser(ctx context.Context, email string, passwordHash string) (uint64, error) {
	ret := _mock.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uint64, error)); ok {
		return returnFunc(ctx, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uint64); ok {
		r0 = returnFunc(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Storage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *Storage_Expecter) CreateUser(ctx interface{}, email interface{}, passwordHash interface{}) *Storage_CreateUser_Call {
	return &Storage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash)}
}

func (_c *Storage_CreateUser_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *Storage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_CreateUser_Call) Return(v uint64, err error) *Storage_CreateUser_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Storage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, email string, passwordHash string) (uint64, error)) *Storage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshHash provides a mock function for the type Storage
func (_mock *Storage) GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (*models.Session, error) {
	ret := _mock.Called(ctx, refreshHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshHash")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*models.Session, error)); ok {
		return returnFunc(ctx, refreshHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *models.Session); ok {
		r0 = returnFunc(ctx, refreshHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, refreshHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetSessionByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshHash'
type Storage_GetSessionByRefreshHash_Call struct {
	*mock.Call
}

// GetSessionByRefreshHash is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshHash []byte
func (_e *Storage_Expecter) GetSessionByRefreshHash(ctx interface{}, refreshHash interface{}) *Storage_GetSessionByRefreshHash_Call {
	return &Storage_GetSessionByRefreshHash_Call{Call: _e.mock.On("GetSessionByRefreshHash", ctx, refreshHash)}
}

func (_c *Storage_GetSessionByRefreshHash_Call) Run(run func(ctx context.Context, refreshHash []byte)) *Storage_GetSessionByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_GetSessionByRefreshHash_Call) Return(session *models.Session, err error) *Storage_GetSessionByRefreshHash_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *Storage_GetSessionByRefreshHash_Call) RunAndReturn(run func(ctx context.Context, refreshHash []byte) (*models.Session, error)) *Storage_GetSessionByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type Storage
func (_mock *Storage) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type Storage_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Storage_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *Storage_GetUserByEmail_Call {
	return &Storage_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *Storage_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *Storage_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_GetUserByEmail_Call) Return(user *models.User, err error) *Storage_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Storage_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *Storage_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessionsByUserID provides a mock function for the type Storage
func (_mock *Storage) RevokeAllSessionsByUserID(ctx context.Context, userID uint64, revokedAt time.Time) error {
	ret := _mock.Called(ctx, userID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessionsByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, revokedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_RevokeAllSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessionsByUserID'
type Storage_RevokeAllSessionsByUserID_Call struct {
	*mock.Call
}

// RevokeAllSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - revokedAt time.Time
func (_e *Storage_Expecter) RevokeAllSessionsByUserID(ctx interface{}, userID interface{}, revokedAt interface{}) *Storage_RevokeAllSessionsByUserID_Call {
	return &Storage_RevokeAllSessionsByUserID_Call{Call: _e.mock.On("RevokeAllSessionsByUserID", ctx, userID, revokedAt)}
}

func (_c *Storage_RevokeAllSessionsByUserID_Call) Run(run func(ctx context.Context, userID uint64, revokedAt time.Time)) *Storage_RevokeAllSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_RevokeAllSessionsByUserID_Call) Return(err error) *Storage_RevokeAllSessionsByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_RevokeAllSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint64, revokedAt time.Time) error) *Storage_RevokeAllSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSessionByID provides a mock function for the type Storage
func (_mock *Storage) RevokeSessionByID(ctx context.Context, sessionID uint64, revokedAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, revokedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_RevokeSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionByID'
type Storage_RevokeSessionByID_Call struct {
	*mock.Call
}

// RevokeSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uint64
//   - revokedAt time.Time
func (_e *Storage_Expecter) RevokeSessionByID(ctx interface{}, sessionID interface{}, revokedAt interface{}) *Storage_RevokeSessionByID_Call {
	return &Storage_RevokeSessionByID_Call{Call: _e.mock.On("RevokeSessionByID", ctx, sessionID, revokedAt)}
}

func (_c *Storage_RevokeSessionByID_Call) Run(run func(ctx context.Context, sessionID uint64, revokedAt time.Time)) *Storage_RevokeSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_RevokeSessionByID_Call) Return(err error) *Storage_RevokeSessionByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_RevokeSessionByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uint64, revokedAt time.Time) error) *Storage_RevokeSessionByID_Call {
	_c.Call.Return(run)
	return _c
}
