// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vbncursed/medialog/auth/internal/models"
)

// NewAuthStorage creates a new instance of AuthStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthStorage {
	mock := &AuthStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthStorage is an autogenerated mock type for the AuthStorage type
type AuthStorage struct {
	mock.Mock
}

type AuthStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthStorage) EXPECT() *AuthStorage_Expecter {
	return &AuthStorage_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type AuthStorage
func (_mock *AuthStorage) CreateUser(ctx context.Context, email string, passwordHash string) (uint64, error) {
	ret := _mock.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uint64, error)); ok {
		return returnFunc(ctx, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uint64); ok {
		r0 = returnFunc(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type AuthStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *AuthStorage_Expecter) CreateUser(ctx interface{}, email interface{}, passwordHash interface{}) *AuthStorage_CreateUser_Call {
	return &AuthStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash)}
}

func (_c *AuthStorage_CreateUser_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *AuthStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthStorage_CreateUser_Call) Return(v uint64, err error) *AuthStorage_CreateUser_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AuthStorage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, email string, passwordHash string) (uint64, error)) *AuthStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type AuthStorage
func (_mock *AuthStorage) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthStorage_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type AuthStorage_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthStorage_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *AuthStorage_GetUserByEmail_Call {
	return &AuthStorage_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *AuthStorage_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *AuthStorage_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthStorage_GetUserByEmail_Call) Return(user *models.User, err error) *AuthStorage_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthStorage_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *AuthStorage_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type AuthStorage
func (_mock *AuthStorage) GetUserByID(ctx context.Context, userID uint64) (*models.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*models.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *models.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthStorage_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type AuthStorage_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *AuthStorage_Expecter) GetUserByID(ctx interface{}, userID interface{}) *AuthStorage_GetUserByID_Call {
	return &AuthStorage_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *AuthStorage_GetUserByID_Call) Run(run func(ctx context.Context, userID uint64)) *AuthStorage_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthStorage_GetUserByID_Call) Return(user *models.User, err error) *AuthStorage_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthStorage_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*models.User, error)) *AuthStorage_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserRole provides a mock function for the type AuthStorage
func (_mock *AuthStorage) UpdateUserRole(ctx context.Context, userID uint64, role string) error {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthStorage_UpdateUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserRole'
type AuthStorage_UpdateUserRole_Call struct {
	*mock.Call
}

// UpdateUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - role string
func (_e *AuthStorage_Expecter) UpdateUserRole(ctx interface{}, userID interface{}, role interface{}) *AuthStorage_UpdateUserRole_Call {
	return &AuthStorage_UpdateUserRole_Call{Call: _e.mock.On("UpdateUserRole", ctx, userID, role)}
}

func (_c *AuthStorage_UpdateUserRole_Call) Run(run func(ctx context.Context, userID uint64, role string)) *AuthStorage_UpdateUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthStorage_UpdateUserRole_Call) Return(err error) *AuthStorage_UpdateUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthStorage_UpdateUserRole_Call) RunAndReturn(run func(ctx context.Context, userID uint64, role string) error) *AuthStorage_UpdateUserRole_Call {
	_c.Call.Return(run)
	return _c
}
