// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vbncursed/medialog/metadata_service/internal/models"
)

// NewMetadataStorage creates a new instance of MetadataStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetadataStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetadataStorage {
	mock := &MetadataStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetadataStorage is an autogenerated mock type for the MetadataStorage type
type MetadataStorage struct {
	mock.Mock
}

type MetadataStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MetadataStorage) EXPECT() *MetadataStorage_Expecter {
	return &MetadataStorage_Expecter{mock: &_m.Mock}
}

// CreateMedia provides a mock function for the type MetadataStorage
func (_mock *MetadataStorage) CreateMedia(ctx context.Context, media *models.Media) error {
	ret := _mock.Called(ctx, media)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Media) error); ok {
		r0 = returnFunc(ctx, media)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MetadataStorage_CreateMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMedia'
type MetadataStorage_CreateMedia_Call struct {
	*mock.Call
}

// CreateMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - media *models.Media
func (_e *MetadataStorage_Expecter) CreateMedia(ctx interface{}, media interface{}) *MetadataStorage_CreateMedia_Call {
	return &MetadataStorage_CreateMedia_Call{Call: _e.mock.On("CreateMedia", ctx, media)}
}

func (_c *MetadataStorage_CreateMedia_Call) Run(run func(ctx context.Context, media *models.Media)) *MetadataStorage_CreateMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Media
		if args[1] != nil {
			arg1 = args[1].(*models.Media)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataStorage_CreateMedia_Call) Return(err error) *MetadataStorage_CreateMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MetadataStorage_CreateMedia_Call) RunAndReturn(run func(ctx context.Context, media *models.Media) error) *MetadataStorage_CreateMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetMedia provides a mock function for the type MetadataStorage
func (_mock *MetadataStorage) GetMedia(ctx context.Context, mediaID uint64) (*models.Media, error) {
	ret := _mock.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for GetMedia")
	}

	var r0 *models.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*models.Media, error)); ok {
		return returnFunc(ctx, mediaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *models.Media); ok {
		r0 = returnFunc(ctx, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataStorage_GetMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMedia'
type MetadataStorage_GetMedia_Call struct {
	*mock.Call
}

// GetMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaID uint64
func (_e *MetadataStorage_Expecter) GetMedia(ctx interface{}, mediaID interface{}) *MetadataStorage_GetMedia_Call {
	return &MetadataStorage_GetMedia_Call{Call: _e.mock.On("GetMedia", ctx, mediaID)}
}

func (_c *MetadataStorage_GetMedia_Call) Run(run func(ctx context.Context, mediaID uint64)) *MetadataStorage_GetMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataStorage_GetMedia_Call) Return(media *models.Media, err error) *MetadataStorage_GetMedia_Call {
	_c.Call.Return(media, err)
	return _c
}

func (_c *MetadataStorage_GetMedia_Call) RunAndReturn(run func(ctx context.Context, mediaID uint64) (*models.Media, error)) *MetadataStorage_GetMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaByExternalID provides a mock function for the type MetadataStorage
func (_mock *MetadataStorage) GetMediaByExternalID(ctx context.Context, source string, externalID string) (*models.Media, error) {
	ret := _mock.Called(ctx, source, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaByExternalID")
	}

	var r0 *models.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.Media, error)); ok {
		return returnFunc(ctx, source, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.Media); ok {
		r0 = returnFunc(ctx, source, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, source, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataStorage_GetMediaByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaByExternalID'
type MetadataStorage_GetMediaByExternalID_Call struct {
	*mock.Call
}

// GetMediaByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
//   - externalID string
func (_e *MetadataStorage_Expecter) GetMediaByExternalID(ctx interface{}, source interface{}, externalID interface{}) *MetadataStorage_GetMediaByExternalID_Call {
	return &MetadataStorage_GetMediaByExternalID_Call{Call: _e.mock.On("GetMediaByExternalID", ctx, source, externalID)}
}

func (_c *MetadataStorage_GetMediaByExternalID_Call) Run(run func(ctx context.Context, source string, externalID string)) *MetadataStorage_GetMediaByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MetadataStorage_GetMediaByExternalID_Call) Return(media *models.Media, err error) *MetadataStorage_GetMediaByExternalID_Call {
	_c.Call.Return(media, err)
	return _c
}

func (_c *MetadataStorage_GetMediaByExternalID_Call) RunAndReturn(run func(ctx context.Context, source string, externalID string) (*models.Media, error)) *MetadataStorage_GetMediaByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMedia provides a mock function for the type MetadataStorage
func (_mock *MetadataStorage) SearchMedia(ctx context.Context, input models.SearchMediaInput) (*models.SearchMediaResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SearchMedia")
	}

	var r0 *models.SearchMediaResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SearchMediaInput) (*models.SearchMediaResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SearchMediaInput) *models.SearchMediaResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchMediaResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.SearchMediaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataStorage_SearchMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMedia'
type MetadataStorage_SearchMedia_Call struct {
	*mock.Call
}

// SearchMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.SearchMediaInput
func (_e *MetadataStorage_Expecter) SearchMedia(ctx interface{}, input interface{}) *MetadataStorage_SearchMedia_Call {
	return &MetadataStorage_SearchMedia_Call{Call: _e.mock.On("SearchMedia", ctx, input)}
}

func (_c *MetadataStorage_SearchMedia_Call) Run(run func(ctx context.Context, input models.SearchMediaInput)) *MetadataStorage_SearchMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SearchMediaInput
		if args[1] != nil {
			arg1 = args[1].(models.SearchMediaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataStorage_SearchMedia_Call) Return(searchMediaResult *models.SearchMediaResult, err error) *MetadataStorage_SearchMedia_Call {
	_c.Call.Return(searchMediaResult, err)
	return _c
}

func (_c *MetadataStorage_SearchMedia_Call) RunAndReturn(run func(ctx context.Context, input models.SearchMediaInput) (*models.SearchMediaResult, error)) *MetadataStorage_SearchMedia_Call {
	_c.Call.Return(run)
	return _c
}
