packages:
  github.com/vbncursed/medialog/auth-service/internal/services/authService:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks.go"
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      Service:
      Storage:

