// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vbncursed/medialog/library_service/internal/models"
)

// NewLibraryStorage creates a new instance of LibraryStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLibraryStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *LibraryStorage {
	mock := &LibraryStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LibraryStorage is an autogenerated mock type for the LibraryStorage type
type LibraryStorage struct {
	mock.Mock
}

type LibraryStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *LibraryStorage) EXPECT() *LibraryStorage_Expecter {
	return &LibraryStorage_Expecter{mock: &_m.Mock}
}

// CreateEntry provides a mock function for the type LibraryStorage
func (_mock *LibraryStorage) CreateEntry(ctx context.Context, entry *models.Entry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Entry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LibraryStorage_CreateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntry'
type LibraryStorage_CreateEntry_Call struct {
	*mock.Call
}

// CreateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *models.Entry
func (_e *LibraryStorage_Expecter) CreateEntry(ctx interface{}, entry interface{}) *LibraryStorage_CreateEntry_Call {
	return &LibraryStorage_CreateEntry_Call{Call: _e.mock.On("CreateEntry", ctx, entry)}
}

func (_c *LibraryStorage_CreateEntry_Call) Run(run func(ctx context.Context, entry *models.Entry)) *LibraryStorage_CreateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Entry
		if args[1] != nil {
			arg1 = args[1].(*models.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LibraryStorage_CreateEntry_Call) Return(err error) *LibraryStorage_CreateEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LibraryStorage_CreateEntry_Call) RunAndReturn(run func(ctx context.Context, entry *models.Entry) error) *LibraryStorage_CreateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function for the type LibraryStorage
func (_mock *LibraryStorage) DeleteEntry(ctx context.Context, entryID uint64, userID uint64) error {
	ret := _mock.Called(ctx, entryID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = returnFunc(ctx, entryID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LibraryStorage_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type LibraryStorage_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID uint64
//   - userID uint64
func (_e *LibraryStorage_Expecter) DeleteEntry(ctx interface{}, entryID interface{}, userID interface{}) *LibraryStorage_DeleteEntry_Call {
	return &LibraryStorage_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, entryID, userID)}
}

func (_c *LibraryStorage_DeleteEntry_Call) Run(run func(ctx context.Context, entryID uint64, userID uint64)) *LibraryStorage_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LibraryStorage_DeleteEntry_Call) Return(err error) *LibraryStorage_DeleteEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LibraryStorage_DeleteEntry_Call) RunAndReturn(run func(ctx context.Context, entryID uint64, userID uint64) error) *LibraryStorage_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntry provides a mock function for the type LibraryStorage
func (_mock *LibraryStorage) GetEntry(ctx context.Context, entryID uint64, userID uint64) (*models.Entry, error) {
	ret := _mock.Called(ctx, entryID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEntry")
	}

	var r0 *models.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*models.Entry, error)); ok {
		return returnFunc(ctx, entryID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *models.Entry); ok {
		r0 = returnFunc(ctx, entryID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, entryID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LibraryStorage_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type LibraryStorage_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID uint64
//   - userID uint64
func (_e *LibraryStorage_Expecter) GetEntry(ctx interface{}, entryID interface{}, userID interface{}) *LibraryStorage_GetEntry_Call {
	return &LibraryStorage_GetEntry_Call{Call: _e.mock.On("GetEntry", ctx, entryID, userID)}
}

func (_c *LibraryStorage_GetEntry_Call) Run(run func(ctx context.Context, entryID uint64, userID uint64)) *LibraryStorage_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LibraryStorage_GetEntry_Call) Return(entry *models.Entry, err error) *LibraryStorage_GetEntry_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *LibraryStorage_GetEntry_Call) RunAndReturn(run func(ctx context.Context, entryID uint64, userID uint64) (*models.Entry, error)) *LibraryStorage_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntries provides a mock function for the type LibraryStorage
func (_mock *LibraryStorage) ListEntries(ctx context.Context, input models.ListEntriesInput) (*models.ListEntriesResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListEntries")
	}

	var r0 *models.ListEntriesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListEntriesInput) (*models.ListEntriesResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListEntriesInput) *models.ListEntriesResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListEntriesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ListEntriesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LibraryStorage_ListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntries'
type LibraryStorage_ListEntries_Call struct {
	*mock.Call
}

// ListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListEntriesInput
func (_e *LibraryStorage_Expecter) ListEntries(ctx interface{}, input interface{}) *LibraryStorage_ListEntries_Call {
	return &LibraryStorage_ListEntries_Call{Call: _e.mock.On("ListEntries", ctx, input)}
}

func (_c *LibraryStorage_ListEntries_Call) Run(run func(ctx context.Context, input models.ListEntriesInput)) *LibraryStorage_ListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ListEntriesInput
		if args[1] != nil {
			arg1 = args[1].(models.ListEntriesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LibraryStorage_ListEntries_Call) Return(listEntriesResult *models.ListEntriesResult, err error) *LibraryStorage_ListEntries_Call {
	_c.Call.Return(listEntriesResult, err)
	return _c
}

func (_c *LibraryStorage_ListEntries_Call) RunAndReturn(run func(ctx context.Context, input models.ListEntriesInput) (*models.ListEntriesResult, error)) *LibraryStorage_ListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntry provides a mock function for the type LibraryStorage
func (_mock *LibraryStorage) UpdateEntry(ctx context.Context, entry *models.Entry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Entry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LibraryStorage_UpdateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntry'
type LibraryStorage_UpdateEntry_Call struct {
	*mock.Call
}

// UpdateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *models.Entry
func (_e *LibraryStorage_Expecter) UpdateEntry(ctx interface{}, entry interface{}) *LibraryStorage_UpdateEntry_Call {
	return &LibraryStorage_UpdateEntry_Call{Call: _e.mock.On("UpdateEntry", ctx, entry)}
}

func (_c *LibraryStorage_UpdateEntry_Call) Run(run func(ctx context.Context, entry *models.Entry)) *LibraryStorage_UpdateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Entry
		if args[1] != nil {
			arg1 = args[1].(*models.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LibraryStorage_UpdateEntry_Call) Return(err error) *LibraryStorage_UpdateEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LibraryStorage_UpdateEntry_Call) RunAndReturn(run func(ctx context.Context, entry *models.Entry) error) *LibraryStorage_UpdateEntry_Call {
	_c.Call.Return(run)
	return _c
}
