packages:
  github.com/vbncursed/medialog/library_service/internal/services/library_service:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks.go"
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      LibraryStorage:

